plugins:
  cppcheck:
    enabled: true
  pylint:
    enabled: true
  pep8:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  gnu-complexity:
    enabled: true
  git-legal:
    enabled: true
exclude_patterns:
- "docs/"
- "docs/*"
- "docs/**"
- "lib/"
- "lib/*"
- "lib/**"
- ".doc/"
- ".github/"