[tool.poetry]
name = "unafold-python"
version = "0.1.3"
description = "Python bindings for UNAFold to determine hybridization energies / folding of RNA/DNA sequences."
authors = ["Piotr Styczyński <piotrs@radcode.co>"]
build = "build.py"
include = [
    "README.md",
    "example",
    "CMakeLists.txt",
    "Makefile",
    "lib",
    "src",
    "data/asint1x2.DAT",
    "data/asint1x2.DG",
    "data/asint1x2.DGD",
    "data/asint1x2.DH",
    "data/asint1x2.DHD",
    "data/asint1x2.NUL",
    "data/asint1x2.NULD",
    "data/asint1x2.NULDAT",
    "data/dangle.DAT",
    "data/dangle.DG",
    "data/dangle.DGD",
    "data/dangle.DH",
    "data/dangle.DHD",
    "data/dangle.NUL",
    "data/dangle.NULD",
    "data/dangle.NULDAT",
    "data/extinction.DAT",
    "data/hexaloop.DAT",
    "data/hexaloop.DG",
    "data/hexaloop.DGD",
    "data/hexaloop.DH",
    "data/hexaloop.DHD",
    "data/hexaloop.NUL",
    "data/hexaloop.NULD",
    "data/hexaloop.NULDAT",
    "data/loop.DAT",
    "data/loop.DG",
    "data/loop.DGD",
    "data/loop.DH",
    "data/loop.DHD",
    "data/loop.NUL",
    "data/loop.NULD",
    "data/loop.NULDAT",
    "data/miscloop.DAT",
    "data/miscloop.DG",
    "data/miscloop.DGD",
    "data/miscloop.DH",
    "data/miscloop.DHD",
    "data/miscloop.NUL",
    "data/miscloop.NULD",
    "data/miscloop.NULDAT",
    "data/sint2.DAT",
    "data/sint2.DG",
    "data/sint2.DGD",
    "data/sint2.DH",
    "data/sint2.DHD",
    "data/sint2.NUL",
    "data/sint2.NULD",
    "data/sint2.NULDAT",
    "data/sint4.DAT",
    "data/sint4.DG",
    "data/sint4.DGD",
    "data/sint4.DH",
    "data/sint4.DHD",
    "data/sint4.NUL",
    "data/sint4.NULD",
    "data/sint4.NULDAT",
    "data/stack.DAT",
    "data/stack.DG",
    "data/stack.DGD",
    "data/stack.DH",
    "data/stack.DHD",
    "data/stack.NUL",
    "data/stack.NULD",
    "data/stack.NULDAT",
    "data/tloop.DAT",
    "data/tloop.DG",
    "data/tloop.DGD",
    "data/tloop.DH",
    "data/tloop.DHD",
    "data/tloop.NUL",
    "data/tloop.NULD",
    "data/tloop.NULDAT",
    "data/triloop.DAT",
    "data/triloop.DG",
    "data/triloop.DGD",
    "data/triloop.DH",
    "data/triloop.DHD",
    "data/triloop.NUL",
    "data/triloop.NULD",
    "data/triloop.NULDAT",
    "data/tstacke.DAT",
    "data/tstacke.DG",
    "data/tstacke.DGD",
    "data/tstacke.DH",
    "data/tstacke.DHD",
    "data/tstacke.NUL",
    "data/tstacke.NULD",
    "data/tstacke.NULDAT",
    "data/tstackh.DAT",
    "data/tstackh.DG",
    "data/tstackh.DGD",
    "data/tstackh.DH",
    "data/tstackh.DHD",
    "data/tstackh.NUL",
    "data/tstackh.NULD",
    "data/tstackh.NULDAT",
    "data/tstacki.DAT",
    "data/tstacki.DG",
    "data/tstacki.DGD",
    "data/tstacki.DH",
    "data/tstacki.DHD",
    "data/tstacki.NUL",
    "data/tstacki.NULD",
    "data/tstacki.NULDAT",
    "data/tstacki23.DAT",
    "data/tstacki23.DG",
    "data/tstacki23.DGD",
    "data/tstacki23.DH",
    "data/tstacki23.DHD",
    "data/tstacki23.NULD",
    "data/tstacki23.NULDAT",
    "data/tstackm.DAT",
    "data/tstackm.DG",
    "data/tstackm.DGD",
    "data/tstackm.DH",
    "data/tstackm.DHD",
    "data/tstackm.NUL",
    "data/tstackm.NULD",
    "data/tstackm.NULDAT"
]

[[tool.poetry.source]]
name = "covid_genomics_pypi"
url = "https://pypi.covidgenomics.com/production/"
default = true

[[tool.poetry.source]]
name = "default_pypi"
url = "https://pypi.python.org/simple/"
secondary = true

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
flakehell = "^0.7.1"
pytest-xdist = "^2.2.0"
isort = "^5.7.0"
black = "^20.8b1"
pydoc-markdown = "^3.9.0"
s3pypi = "^0.11.0"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.flakehell]
exclude = ["README.rst", "README.md", "lib", "build", "dist"]
format = "colored"
max_line_length = 120
show_source = true
whitelist = "../../allowlist.txt"

[tool.flakehell.plugins]
flake8-bandit = ["+*", "-S322"]
flake8-bugbear = ["+*"]
flake8-builtins = ["+*"]
flake8-comprehensions = ["+*"]
flake8-darglint = ["+*"]
flake8-docstrings = ["+*"]
flake8-eradicate = ["+*"]
flake8-isort = ["+*"]
flake8-mutable = ["+*"]
flake8-pytest-style = ["+*"]
flake8-spellcheck = ["+*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*", "-E203", "-W503"]
pyflakes = ["+*", "-E203"]
pylint = ["+*", "-E203"]

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
