name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.7
        with:
          cmake-version: '3.19.x'
      - name: Install Python
        run: |
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends python3.8-dev python3.8-distutils python3.8-venv python3-numpy
          python3.8 -m pip install --upgrade pip setuptools
          python3.8 -m venv $HOME/venv-python3.8
      - name: Install cibuildwheel and numpy
        run: python3.8 -m pip install cibuildwheel==1.8.0 numpy==1.20.1
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            build
            .pytest_cache
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Build wheels
        run: python3.8 -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp27-* pp27-* cp35-* pp35-* cp36-* pp36-* cp37-* pp37-*"  # skip Python 2.7 wheels
      - name: Upload prebuild wheels
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./wheelhouse/*.whl