name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.8.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: "cp27-* pp27-* cp35-* pp35-* cp36-* pp36-* cp37-* pp37-*"  # skip Python 2.7 wheels
          MMSEQ_CMAKE_GENERATOR: "Visual Studio 16 2019 Win32"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl